import type { NextPage } from "next"
import Head from "next/head"
import Hero from "../components/hero"
import Navbar from "../components/navbar"

const Home: NextPage = () => {
  return (
    <div className="flex h-screen w-screen select-none flex-col scrollbar-hide">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="mt-14 h-full flex-col scrollbar-hide">
        <Hero />
        <Hero />
      </div>
    </div>
  )
}

export default Home
