import type { NextPage } from "next"
import Head from "next/head"
import AboutUs from "../components/about-us"
import Footer from "../components/footer"
import Hero from "../components/hero"
import Navbar from "../components/navbar"

const Home: NextPage = () => {
  return (
    <div className="flex h-screen w-screen select-none flex-col scrollbar-hide">
      <Head>
        <title>ESTIEM Budapest BME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-12 h-full flex-col scrollbar-hide">
        <Hero />
        <AboutUs />
        <Footer />
      </div>
      <Navbar />
    </div>
  )
}

export default Home
